### ISSUE TITLE
It fails since Windows 10 upgrade 1511, 10586

### ISSUE THREAD

**Issue by webhsw** [binarymaster/rdpwrap#88] opened 2016-02-11 06:11 UTC
RDPWrapper work not any more since the last Windows 10 ugrade to Version 1511, 10586

**Comment by binarymaster** [comment] 2016-02-11 15:40
Duplicate of https://github.com/binarymaster/rdpwrap/issues/87

**Closed by binarymaster** 2016-02-11 15:40 UTC
Labels: duplicate
