### ISSUE TITLE
Not working with build 10586.3

### ISSUE THREAD

**Issue by ericmoret** [binarymaster/rdpwrap#67] opened 2015-11-16 10:08 UTC
I just upgraded to the latest Windows 10 build and lost the ability to multiple RDP login. I tried reinstalling without success either.

**Comment by binarymaster** [comment] 2015-11-16 10:10
Duplicate of https://github.com/binarymaster/rdpwrap/issues/65

**Closed by binarymaster** 2015-11-16 10:10 UTC
