### ISSUE TITLE
Problem with listener on Windows 10 Home 1511 

### ISSUE THREAD

**Issue by mr-flibble** [binarymaster/rdpwrap#71] opened 2015-12-01 12:22 UTC
Hello, I have problem on WIndows 10 home with latest update. My Windows build is 10586.14
Do you need more information? 

![f814d88c-0fad-4be7-9d58-fe7a72a0a367](https://cloud.githubusercontent.com/assets/5197625/11500529/068885b6-982e-11e5-83ff-c44e4bc48d9c.png)
![fa1425bf-07ce-4ead-ab3a-a704a33425c0](https://cloud.githubusercontent.com/assets/5197625/11500528/06880c76-982e-11e5-8991-1333fba92ce9.png)

**Comment by binarymaster** [comment] 2015-12-01 12:33
Duplicate of https://github.com/binarymaster/rdpwrap/issues/65

Use `update.bat`

**Closed by binarymaster** 2015-12-01 12:33 UTC
Labels: duplicate
