### ISSUE TITLE
New INI doesnt seem to be fully working with Official Windows 10 x64 Home

### ISSUE THREAD

**Issue by alfred0** [binarymaster/rdpwrap#38] opened 2015-07-30 10:51 UTC
![rdpwrap](https://cloud.githubusercontent.com/assets/13570306/8981516/0924865c-3687-11e5-92ce-5363952dc48c.png)

replaced INI, restarted - by the way for those who could not copy the file even if it was elevated that were getting the cryptographic service lock... do it in elevated command prompt. that solved my issue.

i restarted just in case but it it says service is stopped and listener is not listening.

since i am on official upgrade via a dell purchase i can provide ANY file for analyzing if needed.

**Comment by binarymaster** [comment] 2015-07-30 10:54
1. Provide a log file (https://github.com/binarymaster/rdpwrap/issues/34#issuecomment-125620274)
2. Service stopped => it seems to be a crash / software exception => seems to be a duplicate of issue https://github.com/binarymaster/rdpwrap/issues/23

**Comment by alfred0** [comment] 2015-07-30 11:05
pasted here since it said it didnt support attaching the txt file:

>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFECF7F0000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFECF8E23B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF87E00000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF87EF23B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF612B0000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF613A23B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF609C0000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF60AB23B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF612B0000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF613A23B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF610F0000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF611E23B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF5FC10000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF5FD023B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF5CFA0000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF5D0923B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF5AD60000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF5AE523B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF5B710000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF5B8023B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF5B500000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF5B5F23B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF59840000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF599323B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF5D1E0000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF5D2D23B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF5B0E0000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF5B1D23B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFF5D130000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFF5D2223B8] bServerSku = 1

**Comment by binarymaster** [comment] 2015-07-30 11:07
An unknown exception is at SLInit, moved here: https://github.com/binarymaster/rdpwrap/issues/39

**Closed by binarymaster** 2015-07-30 11:07 UTC
