### ISSUE TITLE
Allow Multiple RDP Session in Windows 10 Pro

### ISSUE THREAD

**Issue by ajw107** [binarymaster/rdpwrap#47] opened 2015-08-04 01:43 UTC
Hi
I'm not sure if it's just me being incredibly thick, but I can't seem to get it to allow more than one session in Windows 10 pro.  Everything is green, but I always get the screen saying it must log out the other user first (both with and without one session per user selected, RDP user being a different one from logged in user).

On a side note for anyone still having trouble with ini files, etc.  The easiest thing to do it to download the latest 1.5 version under the Releases header on github, then use the "Download as Zip" button on the main github page to download the whole source as a zip.  Unzip the Release zip, and from the source zip file, in the res folder, copy the two un/install.bat files over the ones in the unzipped release folder.  Then right click and run the install.bat as administrator to install.  Once done, go to the rdpwrap folder in program files and copy into it the rdpwrap.ini from the res folder in the source zip file.  Run rdpconf from the unzipped release zip, and as they say, Bob's your Uncle (whoever Bob is, he he)!
Alex

**Comment by binarymaster** [comment] 2015-08-04 02:18
Seems to be a duplicate of https://github.com/binarymaster/rdpwrap/issues/23

Also see this, maybe it will help: https://github.com/binarymaster/rdpwrap/issues/39#issuecomment-126592057

**Closed by binarymaster** 2015-08-04 02:18 UTC
