### ISSUE TITLE
Windows 10 Pro 10586 - termsrv.dll not supported, help

### ISSUE THREAD

**Issue by lotniak** [binarymaster/rdpwrap#66] opened 2015-11-15 08:27 UTC
Hi

I've updated my Windows 10 Pro to the newest build and wrapper says - termsrv not supported. Can I fix this somehow fast? Dunno, maybe with ini or smth.?

Kind Regards

Lotniak

**Comment by binarymaster** [comment] 2015-11-15 11:26
Duplicate of https://github.com/binarymaster/rdpwrap/issues/65

**Closed by binarymaster** 2015-11-15 11:26 UTC
Labels: duplicate
